### ISSUE TITLE
move to gitlab or gitlab.gnome.org

### ISSUE THREAD

**Issue by spaetz** [spaetz/tootle#5]
Let's move the repo to a friendlier place, such as gitlab or gnome.org. Let us also find a platform to make crowdsourced translations easier.

**Comment by ntonnaett** [comment]
Do you consider submitting it again to Gnome Circle as suggested [here](https://gitlab.gnome.org/Teams/Circle/-/merge_requests/78)?

**Comment by spaetz** [comment]
No, I applied all existing patches that seemed useful, but I have decided that I am not going to continue devlopment. 1) vala is just not my cup of tea and 2) the code base is more or less completely undocumented and hard (for me) to grasp.
